export const theme = {
  colors: {
    grayscale: {
      100: '#FAFAFB',
      200: '#EFEFEF',
      300: '#DEDEDE',
      400: '#A8A8A8',
      500: '#9A9A9A',
      600: '#565656',
      700: '#323232',
      800: '#1F1F1F',
      background: '#F5F6F6',
    },
    brand: {
      primary: '#01D281',
    },
    white: '#fff',
    black: '#000',
    transparent: 'transparent',
  },
  fonts: {
    h1: {
      'font-family': 'Pretendard-Regular',
      'font-size': '26px',
      'line-height': '36px',
      'font-weight': '400',
    },
    h2: {
      'font-family': 'Pretendard-Medium',
      'font-size': '22px',
      'line-height': '30px',
      'font-weight': '500',
    },
    h3: {
      'font-family': 'Pretendard-Bold',
      'font-size': '18px',
      'line-height': '26px',
      'font-weight': '700',
    },
    subtitle1: {
      'font-family': 'Pretendard-Bold',
      'font-size': '16px',
      'line-height': '22px',
      'font-weight': '700',
    },
    body1: {
      'font-family': 'Pretendard-Regular',
      'font-size': '16px',
      'line-height': '22px',
      'font-weight': '400',
    },
    body2: {
      'font-family': 'Pretendard-Regular',
      'font-size': '14px',
      'line-height': '20px',
      'font-weight': '400',
    },
    caption1: {
      'font-family': 'Pretendard-Regular',
      'font-size': '12px',
      'line-height': '18px',
      'font-weight': '400',
    },
    caption2: {
      'font-family': 'Pretendard-Regular',
      'font-size': '11px',
      'line-height': '18px',
      'font-weight': '400',
    },
    button1: {
      'font-family': 'Pretendard-Bold',
      'font-size': '16px',
      'line-height': '24px',
      'font-weight': '700',
    },
    button2: {
      'font-family': 'Pretendard-Bold',
      'font-size': '14px',
      'line-height': '20px',
      'font-weight': '700',
    },
    button3: {
      'font-family': 'Pretendard-Bold',
      'font-size': '12px',
      'line-height': '18px',
      'font-weight': '700',
    },
    webh2: {
      'font-family': 'Pretendard',
      'font-size': '24px',
      'line-height': '34px',
      'font-weight': '700',
    },
  },
};
